services:
  auth-server:
    build:
      context: ./auth-server/server
      dockerfile: Dockerfile
    environment:
      AUTH_MONGODB_URI: mongodb://${AUTH_MONGODB_USER}:${AUTH_MONGODB_PASSWORD}@auth-mongo:${AUTH_MONGODB_PORT}
      AUTH_MONGODB_DB_NAME: ${AUTH_MONGODB_DB_NAME}
      AUTH_SERVER_PORT: ${AUTH_SERVER_PORT}
    ports:
      - 3000:3000
  auth-mongo:
    image: mongo:8.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${AUTH_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${AUTH_MONGODB_PASSWORD}
    ports:
      - ${AUTH_MONGODB_PORT}:27017
    volumes:
      - auth-mongo-data:/data/db
  auth-mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${AUTH_MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${AUTH_MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${AUTH_MONGODB_USER}:${AUTH_MONGODB_PASSWORD}@auth-mongo:${AUTH_MONGODB_PORT}
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - auth-mongo

volumes:
  auth-mongo-data: