services:
  gateway-server:
    build:
      context: ./gateway-server/server
      dockerfile: Dockerfile
    environment:
      AUTH_SERVER_URL: http://auth-server:${AUTH_SERVER_PORT}
      GATEWAY_SERVER_PORT: ${GATEWAY_SERVER_PORT}
      AUTH_SERVER_JWT_SECRET: ${AUTH_SERVER_JWT_SECRET}
    ports:
      - 3000:3000
  auth-server:
    build:
      context: ./auth-server/server
      dockerfile: Dockerfile
    environment:
      AUTH_MONGODB_URI: mongodb://${AUTH_MONGODB_USER}:${AUTH_MONGODB_PASSWORD}@auth-mongo:${AUTH_MONGODB_PORT}
      AUTH_MONGODB_DB_NAME: ${AUTH_MONGODB_DB_NAME}
      AUTH_SERVER_PORT: ${AUTH_SERVER_PORT}
      AUTH_SERVER_ROOT_ADMIN_ID: ${AUTH_SERVER_ROOT_ADMIN_ID}
      AUTH_SERVER_ROOT_ADMIN_PW: ${AUTH_SERVER_ROOT_ADMIN_PW}
      AUTH_SERVER_JWT_SECRET: ${AUTH_SERVER_JWT_SECRET}
  auth-mongo:
    image: mongo:8.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${AUTH_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${AUTH_MONGODB_PASSWORD}
    ports:
      - 27017:${AUTH_MONGODB_PORT}
    volumes:
      - auth-mongo-data:/data/db
  auth-mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${AUTH_MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${AUTH_MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${AUTH_MONGODB_USER}:${AUTH_MONGODB_PASSWORD}@auth-mongo:${AUTH_MONGODB_PORT}
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - auth-mongo
  event-mongo:
    image: mongo:8.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${EVENT_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${EVENT_MONGODB_PASSWORD}
    ports:
      - 27018:${EVENT_MONGODB_PORT}
    volumes:
      - event-mongo-data:/data/db
  event-mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${EVENT_MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${EVENT_MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${EVENT_MONGODB_USER}:${EVENT_MONGODB_PASSWORD}@event-mongo:${EVENT_MONGODB_PORT}
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - event-mongo

volumes:
  auth-mongo-data:
  event-mongo-data: